/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jniDemo_JniDll */

#ifndef _Included_jniDemo_JniDll
#define _Included_jniDemo_JniDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniDemo_JniDll
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jniDemo_JniDll_init
  (JNIEnv *, jobject);

/*
 * Class:     jniDemo_JniDll
 * Method:    put
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_jniDemo_JniDll_put
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     jniDemo_JniDll
 * Method:    get
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jniDemo_JniDll_get
  (JNIEnv *, jobject);

/*
 * Class:     jniDemo_JniDll
 * Method:    callback
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_jniDemo_JniDll_callback
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
